### ISSUE TITLE
Question about data channel, integration time, and min detectable range

### ISSUE THREAD

**Issue by CaptD** [Livox-SDK/Livox-SDK-ROS#1]
Hi, I did some preliminary test with Mid-40 and had three questions:
1. I noticed that the point cloud is published in sensor_msgs/PointCloud format, and there is a "rgb" channel, which is in fact reflectivity. Is it the same concept as intensity data from other lidar? What's its range? Have you tested the lidar with reflective tape? My use case supports installing reflective poles or boards in the environment, and some comments from manufactures are really helpful.
2. An object that is within 1m cannot be detected. Is this a hardware limitation or is it a parameter that I can change?
3. I understood the pattern concept now, and how can I change integration time on firmware or driver level? So I don't have to write a rosnode to do this integration myself.

Thanks for your help.

**Comment by Livox-SDK** [comment]
@CaptD , thanks for your interests in our products. Please see the comments below

1. You are right that the channel named "rgb" is actually the reflectivity, as seen in the source code of Livox-SDK-ROS/src/display_lidar_points/main.cpp on Github. 

The reflectivity differs from the conventional intensity from other LiDARs in the sense that, the intensity of other LiDARs usually refers to the strength (e.g., width/energy) of the returned laser pulse, which varies with multiple factors, such as point distance and incidence angle. The reflectivity returned by Livox LiDARs have compensated all those factors (e.g., distance) but the incidence angle. The returned reflectivity depends only the physical properties (e.g., material) of the object, or the color of the object at the laser wavelength (i.e., 905nm), and the laser incidence angle. If a Lambertian model is assumed on the object, the reflectivity returned by Livox LiDARs would be the object color (at 905nm) times by the cosine value of the laser incidence angle. 

The reflectivity returned by Livox LiDARs is a uint8 number, but then converted to a float32 number when assigned to the channel.value in the Livox SDK. So the range would be from 0 to 255

We do have tested our LiDARs with relfective tapes. If you have any specific question about the test, please let me know.

2. The current firmware truncates all the points within 1m, but we are considering deliver a variant of firmware to retain those points within the range between 0.5m and 1m. The point precision below 1m could be degraded from 2cm to 10cm, typically. If you are interested, please contact our after-sales team at cs@livoxtech.com.

3. The current Linux driver (e.g., Livox-SDK on Github) streams data packets at a constant rate of 1kHz. Each data packet has 100 points and has a 1ms time interval.  To configure the integration time, you may consider using the ROS demo located at Livox-SDK/Livox-SDK-ROS on Github. This demo example runs on the Linux driver, receives points at a rate of 1kHz and display all the points in RVITZ within a given time period. The integration time is given by the macro POINTS_PER_FRAME in the main.cpp, which specifies the number of points within each frame displayed on RVITZ. Another possible way is to use Livox Viewer in Windows. The Livox Viewer supports multiple integration time (i.e., 100ms, 200ms, 500ms, 1s, etc.).

**Comment by CaptD** [comment]
Cool. Awesome. Thanks a lot for your informative feedback. I will try to play with the lidar tomorrow.

**Comment by Livox-SDK** [comment]
@CaptD  we have launched a Q&A forum on google groups: https://groups.google.com/forum/#!forum/livox-lidars. If you have further questions regarding the use of Livox LiDARs, welcome to pose them there. Thanks
