### ISSUE TITLE
catkin_make error on tx2

### ISSUE THREAD

**Issue by jimchenhub** [Livox-SDK/Livox-SDK-ROS#12]
When I catkin_make on tx2, it failed with the following errors:

####
####
Scanning dependencies of target display_hub_points_node
Scanning dependencies of target display_lidar_points_node
[ 25%] Building CXX object display_hub_points/CMakeFiles/display_hub_points_node.dir/main.cpp.o
[ 50%] Building CXX object display_lidar_points/CMakeFiles/display_lidar_points_node.dir/main.cpp.o
/home/dji/Data/github/Livox-SDK-ROS-1.0/src/display_lidar_points/main.cpp: In function ‘void OnDeviceChange(const DeviceInfo*, DeviceEvent)’:
/home/dji/Data/github/Livox-SDK-ROS-1.0/src/display_lidar_points/main.cpp:309:61: error: invalid conversion from ‘void (*)(uint8_t, uint8_t, DeviceInformationResponse*, void*) {aka void (*)(unsigned char, unsigned char, DeviceInformationResponse*, void*)}’ to ‘DeviceInformationCallback {aka void (*)(int, unsigned char, DeviceInformationResponse*, void*)}’ [-fpermissive]
     QueryDeviceInformation(handle, OnDeviceInformation, NULL);

How can I solve this problem?

**Comment by Livox-SDK** [comment]
The Livox-SDK-ROS project is deprecated, Please Use livox_ros_driver instead!
The livox_ros_driver link is as below: 
https://github.com/Livox-SDK/livox_ros_driver

**Comment by jimchenhub** [comment]
Thanks for your help.
